name: basic_logger_file
description: FileOutputLogger adds file logging to BasicLogger for Android, iOS, Linux, macOS, and Windows.
version: 0.1.3
repository: https://github.com/huanguan1978/basic_logger_file.git
homepage: https://github.com/huanguan1978/basic_logger_file

topics:
  - logging
  - console
  - debug
  - user-logs

# publish_to: 'none'

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  basic_logger: ^0.2.2
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
